name: Scrape and Upload

on:
  # schedule:
  #   - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas datadotworld

      - name: Scrape data
        run: python scripts/scrape.py

      - name: Aggregate hourly
        run: python scripts/aggregate.py

      - name: Upload to data.world
        env:
          DW_AUTH_TOKEN: ${{ secrets.DATA_WORLD_API_TOKEN }}
        run: python scripts/upload.py
